name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-aab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # BURASI ÇOK KRİTİK: Sürümü tırnak içinde ve net yazıyoruz
          flutter-version: '3.24.5' 
          channel: 'stable'
          cache: false # Önbelleği tamamen kapatıyoruz, zorla temiz kurulum yaptıracağız

      - name: Flutter Clean & Pub Get
        run: |
          flutter clean
          flutter pub cache clean --force
          flutter pub get

      - name: Build appbundle
        # Keystore (Şifre) bilgilerini bozmadan buraya ekliyoruz:
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: flutter build appbundle --release --no-tree-shake-icons --no-pub

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: build/app/outputs/bundle/release/app-release.aab
