name: YeniBuild Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Force Manual Flutter Install
        run: |
          # GitHub'ın kendi Flutter'ını görmezden gelmesi için manuel indiriyoruz
          git clone https://github.com/flutter/flutter.git -b 3.24.5 --depth 1
          # PATH ayarını GitHub'ın yüklü olan sürümünün önüne geçecek şekilde yapıyoruz
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Verify Flutter Version
        run: flutter --version # Burada 3.24.5 yazmazsa sistemde bir sorun var demektir

      - name: Build appbundle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          flutter pub get
          # Doğrudan indirdiğimiz flutter ile build alıyoruz
          flutter build appbundle --release --no-tree-shake-icons
