name: YeniBuild Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Force Manual Flutter Install
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.24.5 --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "FLUTTER_ROOT=$GITHUB_WORKSPACE/flutter" >> $GITHUB_ENV

      - name: Build appbundle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          # 1. Android'e Flutter'ın yerini fısıldıyoruz
          echo "flutter.sdk=$GITHUB_WORKSPACE/flutter" > android/local.properties
          echo "sdk.dir=/usr/local/lib/android/sdk" >> android/local.properties
          
          # 2. Temizlik ve Bağımlılıklar
          ./flutter/bin/flutter clean
          ./flutter/bin/flutter pub get
          
          # 3. Build (Tam yol kullanarak)
          ./flutter/bin/flutter build appbundle --release --no-tree-shake-icons

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
