name: YeniBuild Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Force Manual Flutter Install
        run: |
          git clone https://github.com/flutter/flutter.git -b 3.24.5 --depth 1
          # Path ayarını bu adımda yapıyoruz
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - name: Build appbundle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          # DİKKAT: Tam yol belirterek sistemi zorluyoruz
          ./flutter/bin/flutter clean
          ./flutter/bin/flutter pub get
          ./flutter/bin/flutter build appbundle --release --no-tree-shake-icons
          
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
